### ISSUE TITLE
[Warnings] On Compile

### ISSUE THREAD

**Issue by Comicsanswich** [EfeDursun125/TF2-EBOTS#10]
It compiles just fine but gives these warnings forgot to make an issue about that yesterday after compiling and testing the latest update to ebots just showing ya and letting ya know just in case here's the screenshot.
![image_2023-02-05_150943792](https://user-images.githubusercontent.com/28740793/216842337-2e517c62-ca6b-4c73-8a96-be0212554eaa.png)

**Comment by EfeDursun125** [comment]
because these gamemodes not implemented yet, warning doesn't mean error and this warrning are the most fine one just saying these variables are defined but not used anywhere.

**Comment by Comicsanswich** [comment]
I see thanks for telling me this I'll close this now.
