### ISSUE TITLE
[New version] Medic bots cause extreme lag

### ISSUE THREAD

**Issue by Samg381** [EfeDursun125/TF2-EBOTS#13]
Ebots using the medic class lag the server greatly. All other classes work well.

**Comment by EfeDursun125** [comment]
new version is desinged to be use waypoints only, now i have switched cbasenpc for high performance navmesh pathfinding redownload ebots and try again.

**Comment by Samg381** [comment]
Thank you!! I will redownlod again this evening and let you know

**Comment by Samg381** [comment]
Ok, update. The navmesh works a lot better. Some bots get stuck on the glass in spawn on ctf_doublecross.

**Comment by Samg381** [comment]
I think the second error (bots stuck walking in circles on capture point) might be caused by this line:

https://github.com/EfeDursun125/TF2-EBOTS/blob/d0b609030b60c5ce30044203abf5628c5ed8200d/NewVersion/include/ebotai/goap/defaultai.inc#L771

**Comment by Samg381** [comment]
The medic bot lag is fixed with the latest update!
