### ISSUE TITLE
[URGENT] [New version] Bots get stuck walking in circles on capture point

### ISSUE THREAD

**Issue by Samg381** [EfeDursun125/TF2-EBOTS#14]
In CTF maps, after the bot captures the intel, they will become stuck walking around in circles on top of the capture point.

Troubleshooting tip:
- If I hit noclip while the bot is stuck on the capture point, the bot starts working normally again

I think it may have something to do with this line:

https://github.com/EfeDursun125/TF2-EBOTS/blob/d0b609030b60c5ce30044203abf5628c5ed8200d/NewVersion/include/ebotai/goap/defaultai.inc#L772C84-L772C84

**Comment by EfeDursun125** [comment]
do not reload ebots while ctf map is running on the server

**Comment by Samg381** [comment]
I'm sorry, I don't understand. I am using the bots as normal. When they get to a capture point, they walk in circles on top of it. This can be seen on ctf_2fort and ctf_turbine.

**Comment by Samg381** [comment]
[Here is a video of the circle walking behavior]()

**Comment by EfeDursun125** [comment]
i mean do not use "sm plugins reload tf2_ebot" command in ctf map, turbine waypoints aren't made by me, i'll check

**Comment by Samg381** [comment]
Oh, I see. I have observed the capture point behavior very frequently **on every ctf map**, and without ever reloading if that helps.

**Comment by Samg381** [comment]
[Here is another video]()

**Comment by Samg381** [comment]
Issue resolved. Closing.
