### ISSUE TITLE
[Feature] Switch to SMExt-TF2Items instead of TF2Items

### ISSUE THREAD

**Issue by Dragonissa** [EfeDursun125/TF2-EBOTS#18]
TF2Items is basically dead.

https://github.com/nosoop/SMExt-TF2Items

**Comment by EfeDursun125** [comment]
is it broken with the new update?

**Comment by Dragonissa** [comment]
Doubt it is, but it hasn't been touched since last year. Its more of a nice to have since it gonna be deprecated at some point.

**Comment by Dragonissa** [comment]
Just rechecked with nosoop. There is no need to recompile it with smex-tf2items, its a dropin replacement. 

So it might be a better idea to just mention or link the fork.
