### ISSUE TITLE
Can this mod trigger VAC?

### ISSUE THREAD

**Issue by T-Rizzle12** [EfeDursun125/TF2-EBOTS#2]
I know that the VAC for TF2 is out of date, but you still use VAC to collect random item drops.

**Comment by EfeDursun125** [comment]
what do you mean? this is legal serverside plugin, only can be used in servers running sourcemod. No one can get banned for using this

**Comment by T-Rizzle12** [comment]
My Mistake, I'm going to add it to the server now
