### ISSUE TITLE
[Errors] Auto Waypoint is broken

### ISSUE THREAD

**Issue by Comicsanswich** [EfeDursun125/TF2-EBOTS#9]
When using waypoint auto it shows these errors
![image_2023-01-30_131152477](https://user-images.githubusercontent.com/28740793/215560526-4d921ecb-3f85-4251-b3c7-e394688fe95f.png)
May be caused by the latest version of tf2 I've checked and have every requirement for ebots and all of them are up to date I'm also using the latest stable version of sourcemod and metamod.

**Comment by EfeDursun125** [comment]
try it again, i updated the plugin

**Comment by Comicsanswich** [comment]
> try it again, i updated the plugin

It's been fixed thank you so much I'll close this now and if I see these errors again after a new tf2 update I'll reopen this.
